### ISSUE TITLE
Support generic OTLP exporter env vars (endpoint & insecure)

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/opentelemetry-go-contrib#421]
Add support for setting generic OTLP endpoint and insecure env vars and using them when configuring the traces and metrics exports.

- `OTEL_EXPORTER_OTLP_ENDPOINT`
- `OTEL_EXPORTER_OTLP_INSECURE`

**Comment by MikeGoldsmith** [comment]
Will be closed by: https://github.com/honeycombio/opentelemetry-go-contrib/pull/620
